name: engawa
root: /Users/bthode/Code/engawa

windows:
  - main:
      layout: aecc,364x85,0,0[364x24,0,0,65,364x60,0,25{90x60,0,25,66,90x60,91,25,67,90x60,182,25,68,91x60,273,25,69}]
      panes:
        -
        - cd ui && yarn dev
        - cd ui && yarn test --watch
        - cd api && hatch run ptw
        - cd api && hatch run dev
