name: engawa
root: /Users/bthode/Code/engawa

windows:
  - main:
      layout: aecc,364x85,0,0[364x24,0,0,65,364x60,0,25{90x60,0,25,66,90x60,91,25,67,90x60,182,25,68,91x60,273,25,69}]
      panes:
        -
        - cd ui && yarn dev
        - cd ui && yarn test --watch
        - cd api && hatch run ptw
        - cd api && hatch run dev



#on_project_start: hatch shell
# windows:
#   - main:
    #layout: 5523,364x85,0,0[364x29,0,0,41,364x55,0,30{120x55,0,30,42,120x55,121,30,48,122x55,242,30,46}
      # layout: 968b,255x64,0,0{172x64,0,0,1,82x64,173,0,3}
      # panes:
      #   - cd ui && yarn dev
      #   - cd ui && yarn test --watch
      #   - cd api && hatch run ptw
      #   - cd api && hatch run dev
