/* eslint-disable */
/**
 * Engawa
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChannelInfo
 */
export interface ChannelInfo {
    /**
     * 
     * @type {number}
     * @memberof ChannelInfo
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ChannelInfo
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelInfo
     */
    rssLink: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelInfo
     */
    imageLink: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelInfo
     */
    description: string;
}

/**
 * Check if a given object implements the ChannelInfo interface.
 */
export function instanceOfChannelInfo(value: object): value is ChannelInfo {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('rssLink' in value) || value['rssLink'] === undefined) return false;
    if (!('imageLink' in value) || value['imageLink'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ChannelInfoFromJSON(json: any): ChannelInfo {
    return ChannelInfoFromJSONTyped(json, false);
}

export function ChannelInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'],
        'rssLink': json['rss_link'],
        'imageLink': json['image_link'],
        'description': json['description'],
    };
}

  export function ChannelInfoToJSON(json: any): ChannelInfo {
      return ChannelInfoToJSONTyped(json, false);
  }

  export function ChannelInfoToJSONTyped(value?: ChannelInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'rss_link': value['rssLink'],
        'image_link': value['imageLink'],
        'description': value['description'],
    };
}

