/* tslint:disable */
/* eslint-disable */
/**
 * Engawa
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ComparisonOperator = {
    Lt: 'lt',
    Le: 'le',
    Eq: 'eq',
    Ne: 'ne',
    Ge: 'ge',
    Gt: 'gt'
} as const;
export type ComparisonOperator = typeof ComparisonOperator[keyof typeof ComparisonOperator];


export function instanceOfComparisonOperator(value: any): boolean {
    for (const key in ComparisonOperator) {
        if (Object.prototype.hasOwnProperty.call(ComparisonOperator, key)) {
            if (ComparisonOperator[key as keyof typeof ComparisonOperator] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ComparisonOperatorFromJSON(json: any): ComparisonOperator {
    return ComparisonOperatorFromJSONTyped(json, false);
}

export function ComparisonOperatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComparisonOperator {
    return json as ComparisonOperator;
}

export function ComparisonOperatorToJSON(value?: ComparisonOperator | null): any {
    return value as any;
}

export function ComparisonOperatorToJSONTyped(value: any, ignoreDiscriminator: boolean): ComparisonOperator {
    return value as ComparisonOperator;
}

