/* tslint:disable */
/* eslint-disable */
/**
 * Engawa
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ErrorState = {
    Unauthorized: 'unauthorized',
    Timeout: 'timeout',
    Refused: 'refused'
} as const;
export type ErrorState = typeof ErrorState[keyof typeof ErrorState];


export function instanceOfErrorState(value: any): boolean {
    for (const key in ErrorState) {
        if (Object.prototype.hasOwnProperty.call(ErrorState, key)) {
            if (ErrorState[key as keyof typeof ErrorState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ErrorStateFromJSON(json: any): ErrorState {
    return ErrorStateFromJSONTyped(json, false);
}

export function ErrorStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorState {
    return json as ErrorState;
}

export function ErrorStateToJSON(value?: ErrorState | null): any {
    return value as any;
}

export function ErrorStateToJSONTyped(value: any, ignoreDiscriminator: boolean): ErrorState {
    return value as ErrorState;
}

