/* eslint-disable */
/**
 * Engawa
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MetadataErrorType = {
    LiveEventNotStarted: 'Live event not started',
    VideoUnavailable: 'Video unavailable',
    CopyrightStrike: 'Copyright strike',
    UnknownError: 'Unknown error',
    AgeRestricted: 'Age restricted'
} as const;
export type MetadataErrorType = typeof MetadataErrorType[keyof typeof MetadataErrorType];


export function instanceOfMetadataErrorType(value: any): boolean {
    for (const key in MetadataErrorType) {
        if (Object.prototype.hasOwnProperty.call(MetadataErrorType, key)) {
            if (MetadataErrorType[key as keyof typeof MetadataErrorType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MetadataErrorTypeFromJSON(json: any): MetadataErrorType {
    return MetadataErrorTypeFromJSONTyped(json, false);
}

export function MetadataErrorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataErrorType {
    return json as MetadataErrorType;
}

export function MetadataErrorTypeToJSON(value?: MetadataErrorType | null): any {
    return value as any;
}

export function MetadataErrorTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): MetadataErrorType {
    return value as MetadataErrorType;
}

