/* eslint-disable */
/**
 * Engawa
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlexLibraryDestination
 */
export interface PlexLibraryDestination {
    /**
     * 
     * @type {number}
     * @memberof PlexLibraryDestination
     */
    locationId: number;
    /**
     * 
     * @type {number}
     * @memberof PlexLibraryDestination
     */
    directoryId: number;
}

/**
 * Check if a given object implements the PlexLibraryDestination interface.
 */
export function instanceOfPlexLibraryDestination(value: object): value is PlexLibraryDestination {
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    if (!('directoryId' in value) || value['directoryId'] === undefined) return false;
    return true;
}

export function PlexLibraryDestinationFromJSON(json: any): PlexLibraryDestination {
    return PlexLibraryDestinationFromJSONTyped(json, false);
}

export function PlexLibraryDestinationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlexLibraryDestination {
    if (json == null) {
        return json;
    }
    return {
        
        'locationId': json['locationId'],
        'directoryId': json['directoryId'],
    };
}

  export function PlexLibraryDestinationToJSON(json: any): PlexLibraryDestination {
      return PlexLibraryDestinationToJSONTyped(json, false);
  }

  export function PlexLibraryDestinationToJSONTyped(value?: PlexLibraryDestination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'locationId': value['locationId'],
        'directoryId': value['directoryId'],
    };
}

