/* tslint:disable */
/* eslint-disable */
/**
 * Engawa
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequirementStatus
 */
export interface RequirementStatus {
    /**
     * 
     * @type {string}
     * @memberof RequirementStatus
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof RequirementStatus
     */
    available: boolean;
    /**
     * 
     * @type {string}
     * @memberof RequirementStatus
     */
    path: string | null;
}

/**
 * Check if a given object implements the RequirementStatus interface.
 */
export function instanceOfRequirementStatus(value: object): value is RequirementStatus {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('available' in value) || value['available'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function RequirementStatusFromJSON(json: any): RequirementStatus {
    return RequirementStatusFromJSONTyped(json, false);
}

export function RequirementStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequirementStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'available': json['available'],
        'path': json['path'],
    };
}

  export function RequirementStatusToJSON(json: any): RequirementStatus {
      return RequirementStatusToJSONTyped(json, false);
  }

  export function RequirementStatusToJSONTyped(value?: RequirementStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'available': value['available'],
        'path': value['path'],
    };
}

