/* tslint:disable */
/* eslint-disable */
/**
 * Engawa
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RequirementStatus } from './RequirementStatus';
import {
    RequirementStatusFromJSON,
    RequirementStatusFromJSONTyped,
    RequirementStatusToJSON,
    RequirementStatusToJSONTyped,
} from './RequirementStatus';

/**
 * 
 * @export
 * @interface RequirementsCheckResult
 */
export interface RequirementsCheckResult {
    /**
     * 
     * @type {RequirementStatus}
     * @memberof RequirementsCheckResult
     */
    ffmpeg: RequirementStatus;
    /**
     * 
     * @type {RequirementStatus}
     * @memberof RequirementsCheckResult
     */
    ffprobe: RequirementStatus;
}

/**
 * Check if a given object implements the RequirementsCheckResult interface.
 */
export function instanceOfRequirementsCheckResult(value: object): value is RequirementsCheckResult {
    if (!('ffmpeg' in value) || value['ffmpeg'] === undefined) return false;
    if (!('ffprobe' in value) || value['ffprobe'] === undefined) return false;
    return true;
}

export function RequirementsCheckResultFromJSON(json: any): RequirementsCheckResult {
    return RequirementsCheckResultFromJSONTyped(json, false);
}

export function RequirementsCheckResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequirementsCheckResult {
    if (json == null) {
        return json;
    }
    return {
        
        'ffmpeg': RequirementStatusFromJSON(json['ffmpeg']),
        'ffprobe': RequirementStatusFromJSON(json['ffprobe']),
    };
}

  export function RequirementsCheckResultToJSON(json: any): RequirementsCheckResult {
      return RequirementsCheckResultToJSONTyped(json, false);
  }

  export function RequirementsCheckResultToJSONTyped(value?: RequirementsCheckResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ffmpeg': RequirementStatusToJSON(value['ffmpeg']),
        'ffprobe': RequirementStatusToJSON(value['ffprobe']),
    };
}

