/* tslint:disable */
/* eslint-disable */
/**
 * Engawa
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RetentionType = {
    DateSince: 'DateSince',
    Count: 'Count',
    Delta: 'Delta'
} as const;
export type RetentionType = typeof RetentionType[keyof typeof RetentionType];


export function instanceOfRetentionType(value: any): boolean {
    for (const key in RetentionType) {
        if (Object.prototype.hasOwnProperty.call(RetentionType, key)) {
            if (RetentionType[key as keyof typeof RetentionType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RetentionTypeFromJSON(json: any): RetentionType {
    return RetentionTypeFromJSONTyped(json, false);
}

export function RetentionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetentionType {
    return json as RetentionType;
}

export function RetentionTypeToJSON(value?: RetentionType | null): any {
    return value as any;
}

export function RetentionTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): RetentionType {
    return value as RetentionType;
}

