/* tslint:disable */
/* eslint-disable */
/**
 * Engawa
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RetentionType } from './RetentionType';
import {
    RetentionTypeFromJSON,
    RetentionTypeFromJSONTyped,
    RetentionTypeToJSON,
    RetentionTypeToJSONTyped,
} from './RetentionType';

/**
 * 
 * @export
 * @interface RetentionPolicyModel
 */
export interface RetentionPolicyModel {
    /**
     * 
     * @type {number}
     * @memberof RetentionPolicyModel
     */
    id?: number;
    /**
     * 
     * @type {RetentionType}
     * @memberof RetentionPolicyModel
     */
    type: RetentionType;
    /**
     * 
     * @type {number}
     * @memberof RetentionPolicyModel
     */
    videoCount: number;
    /**
     * 
     * @type {Date}
     * @memberof RetentionPolicyModel
     */
    dateBefore: Date;
    /**
     * 
     * @type {string}
     * @memberof RetentionPolicyModel
     */
    timeDeltaTypeValue: string;
}



/**
 * Check if a given object implements the RetentionPolicyModel interface.
 */
export function instanceOfRetentionPolicyModel(value: object): value is RetentionPolicyModel {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('videoCount' in value) || value['videoCount'] === undefined) return false;
    if (!('dateBefore' in value) || value['dateBefore'] === undefined) return false;
    if (!('timeDeltaTypeValue' in value) || value['timeDeltaTypeValue'] === undefined) return false;
    return true;
}

export function RetentionPolicyModelFromJSON(json: any): RetentionPolicyModel {
    return RetentionPolicyModelFromJSONTyped(json, false);
}

export function RetentionPolicyModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetentionPolicyModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': RetentionTypeFromJSON(json['type']),
        'videoCount': json['videoCount'],
        'dateBefore': (new Date(json['dateBefore'])),
        'timeDeltaTypeValue': json['timeDeltaTypeValue'],
    };
}

  export function RetentionPolicyModelToJSON(json: any): RetentionPolicyModel {
      return RetentionPolicyModelToJSONTyped(json, false);
  }

  export function RetentionPolicyModelToJSONTyped(value?: RetentionPolicyModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': RetentionTypeToJSON(value['type']),
        'videoCount': value['videoCount'],
        'dateBefore': ((value['dateBefore']).toISOString().substring(0,10)),
        'timeDeltaTypeValue': value['timeDeltaTypeValue'],
    };
}

