/* tslint:disable */
/* eslint-disable */
/**
 * Engawa
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Filter } from './Filter';
import {
    FilterFromJSON,
    FilterFromJSONTyped,
    FilterToJSON,
    FilterToJSONTyped,
} from './Filter';
import type { PlexLibraryDestination } from './PlexLibraryDestination';
import {
    PlexLibraryDestinationFromJSON,
    PlexLibraryDestinationFromJSONTyped,
    PlexLibraryDestinationToJSON,
    PlexLibraryDestinationToJSONTyped,
} from './PlexLibraryDestination';
import type { RetentionPolicyModel } from './RetentionPolicyModel';
import {
    RetentionPolicyModelFromJSON,
    RetentionPolicyModelFromJSONTyped,
    RetentionPolicyModelToJSON,
    RetentionPolicyModelToJSONTyped,
} from './RetentionPolicyModel';

/**
 * 
 * @export
 * @interface SubscriptionCreateV2
 */
export interface SubscriptionCreateV2 {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCreateV2
     */
    url: string;
    /**
     * 
     * @type {Array<Filter>}
     * @memberof SubscriptionCreateV2
     */
    filters?: Array<Filter>;
    /**
     * 
     * @type {RetentionPolicyModel}
     * @memberof SubscriptionCreateV2
     */
    retentionPolicy: RetentionPolicyModel;
    /**
     * 
     * @type {PlexLibraryDestination}
     * @memberof SubscriptionCreateV2
     */
    plexLibraryDestination: PlexLibraryDestination;
}

/**
 * Check if a given object implements the SubscriptionCreateV2 interface.
 */
export function instanceOfSubscriptionCreateV2(value: object): value is SubscriptionCreateV2 {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('retentionPolicy' in value) || value['retentionPolicy'] === undefined) return false;
    if (!('plexLibraryDestination' in value) || value['plexLibraryDestination'] === undefined) return false;
    return true;
}

export function SubscriptionCreateV2FromJSON(json: any): SubscriptionCreateV2 {
    return SubscriptionCreateV2FromJSONTyped(json, false);
}

export function SubscriptionCreateV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionCreateV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'filters': json['filters'] == null ? undefined : ((json['filters'] as Array<any>).map(FilterFromJSON)),
        'retentionPolicy': RetentionPolicyModelFromJSON(json['retentionPolicy']),
        'plexLibraryDestination': PlexLibraryDestinationFromJSON(json['plexLibraryDestination']),
    };
}

  export function SubscriptionCreateV2ToJSON(json: any): SubscriptionCreateV2 {
      return SubscriptionCreateV2ToJSONTyped(json, false);
  }

  export function SubscriptionCreateV2ToJSONTyped(value?: SubscriptionCreateV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'filters': value['filters'] == null ? undefined : ((value['filters'] as Array<any>).map(FilterToJSON)),
        'retentionPolicy': RetentionPolicyModelToJSON(value['retentionPolicy']),
        'plexLibraryDestination': PlexLibraryDestinationToJSON(value['plexLibraryDestination']),
    };
}

