/* eslint-disable */
/**
 * Engawa
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionCreate
 */
export interface SubscriptionCreate {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCreate
     */
    url: string;
}

/**
 * Check if a given object implements the SubscriptionCreate interface.
 */
export function instanceOfSubscriptionCreate(value: object): value is SubscriptionCreate {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function SubscriptionCreateFromJSON(json: any): SubscriptionCreate {
    return SubscriptionCreateFromJSONTyped(json, false);
}

export function SubscriptionCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

  export function SubscriptionCreateToJSON(json: any): SubscriptionCreate {
      return SubscriptionCreateToJSONTyped(json, false);
  }

  export function SubscriptionCreateToJSONTyped(value?: SubscriptionCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

