[version]
path = "src/engawa/__about__.py"

# TODO: Split these out enough so that we can know which linter / check fails in Github Actions
[envs.default.scripts]
typing = "pyright {args}"
lint = "ruff check {args:.}"
style = ["ruff check .", "black --check --diff ."]
fmt = ["black .", "ruff check --fix .", "style"]
ptw = "pytest-watch {args}"
test = "pytest {args}"
dev = "uvicorn app.main:app --port 8000 --reload"
debug = "python -Xfrozen_modules=off -m debugpy --listen 5678 --wait-for-client -m uvicorn app.main:app --reload"
all = ["style", "typing"]
