name: Client Python Package

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install Hatch
        run: pipx install hatch
      - name: Run tests
        run: hatch run test:test
      - name: Run linting
        run: hatch run lint
